# Generated by Django 6.0.3 on 2026-04-09 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EdoCita',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EdoCuenta',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoTerapia',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=100)),
                ('horas', models.CharField(max_length=100)),
                ('icono', models.CharField(default='sun', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePila', models.CharField(max_length=50)),
                ('primerApellido', models.CharField(max_length=50)),
                ('segundoApellido', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('fotoPerfil', models.ImageField(blank=True, default='perfiles/default.png', null=True, upload_to='perfiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('estadoCuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultorio.edocuenta')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.tipousuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('notas', models.TextField()),
                ('diagnostico', models.TextField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.cita')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.edocita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='grupoTerapia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultorio.grupoterapia'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEnvio', models.DateTimeField()),
                ('contenido', models.TextField()),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.conversacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.modalidad'),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fechaNacimiento', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateField()),
                ('antecedentes', models.TextField()),
                ('traumas', models.TextField()),
                ('sintomas', models.TextField()),
                ('evolucion', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEmision', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=50)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.especialidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.psicologo'),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.servicio'),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('numSesion', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('numTel', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConvUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.conversacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('conversacion', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='GrupoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoTerapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.grupoterapia')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'grupoTerapia')},
            },
        ),
        migrations.CreateModel(
            name='HorPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.horario')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.psicologo')),
            ],
            options={
                'unique_together': {('psicologo', 'horario')},
            },
        ),
    ]
