# Generated by Django 6.0.3 on 2026-04-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='dirCalle',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='dirColonia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='dirNum',
        ),
    ]
