# Generated by Django 6.0.3 on 2026-04-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='es_grupal_posible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio',
            name='especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='consultorio.especialidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='max_personas',
            field=models.IntegerField(default=1),
        ),
    ]
