# Generated by Django 6.0.3 on 2026-04-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0002_servicio_es_grupal_posible_servicio_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
