# Generated by Django 6.0.3 on 2026-04-19 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_mensaje_leido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='antecedentes',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='evolucion',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='sintomas',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='numSesion',
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='riesgos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='sesion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consultorio.sesion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologo',
            name='presentacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='conducta',
            field=models.TextField(default='Un poco alterado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='diagnostico',
            field=models.TextField(default='Talvez tengo problemas de autoestima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='notas',
            field=models.TextField(default='Siempre intenta agradar a los demas sin prestar atencion a su propio bienestar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='resumen',
            field=models.TextField(default='Padece del sindrome del heroe'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('personales', models.TextField()),
                ('psicologicos', models.TextField()),
                ('familiares', models.TextField()),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='EdoEmocional',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('ansiedad', models.IntegerField()),
                ('tristeza', models.IntegerField()),
                ('estres', models.IntegerField()),
                ('animo_general', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('notas', models.TextField()),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTrabajo',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('objetivos', models.TextField()),
                ('frecuencia_sesion', models.CharField(max_length=50)),
                ('tecnicas', models.TextField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.sesion')),
            ],
        ),
    ]
